name: Create Installer for Node-RED

on:
  release:
    types: [published]
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Run Inno Compiler
      run: iscc "nodered.iss"
    
    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2
      with:
        repo_token: ${{ secrets.NODE_RED_INSTALLER }}
        file: "installer\Output\Node-RED Installer.exe"
        asset_name: "Node-Red Installer.exe"
        tag: ${{ github.ref }}
        overwrite: true