name: Create Installer for Node-RED

on:
  release:
    types: [published]
    
  workflow_dispatch:
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Run Inno Compiler
      run: iscc "nodered.iss"
    
    - name: CodeSign the installer 
      uses: dlemstra/code-sign-action@v1
      if: ${{ vars.SIGN_INSTALLER == 'TRUE' }}
      with:
        certificate: '${{ secrets.CODE_SIGNING_CERTIFICATE }}'
        password: '${{ secrets.CODE_SIGNING_CERTIFICATE_PASSWORD }}'
        folder: 'Output'
        recursive: false
        files: |
          Node-RED.Installer.exe

    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2.5.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Output\Node-RED Installer.exe
        asset_name: "Node-Red Installer.exe"
        tag: ${{ github.ref }}
        overwrite: true